pipeline {
    agent any

    environment {
        BRANCH_NAME = "${GIT_BRANCH.split("/")[1]}"
        ORIGIN_WORKSPACE = pwd()
        SERVICE_NAME = "fe-cloud-cms"
        PROJECT_NAME = "course-cms" // 名称显示在镜像名称
        PROJECT_PATH = "./"
        ENV_NAME = 'dev'
        JELLYFISH_BRANCH = 'birdflock'
    }

    stages {
        stage('Branch') {
            steps {
                sh 'git checkout ${BRANCH_NAME}'
                sh 'git pull'
            }
        }
        stage('Upload') {
            steps {
                archiveArtifactsToQiniu allowEmptyArchive: false, caseSensitive: false, excludeFilesGlob: '', includeFilesGlob: 'dist/cms/**/*', onlyIfSuccessful: true, useDefaultExcludes: false, objectNamePrefix: 'ufe/cloud/assets/', deleteFilePathPrefix: 'dist/cms/cdn-assets/'
            }
        }
    }

    post {
        success {
            echo 'I successed! Push new tag.'
        }
        failure {
            echo 'I failed :(. Reset git head.'
        }
    }
}

